[package]
name = "mp-game-test-common"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.95"
byteorder = "1.5.0"
log = "0.4.25"
tracing-subscriber = "0.3.19"

int-enum = "1.1.2"
bitflags = "2.8.0"
simple_moving_average = "1.0.2"
zstd = "0.13.3"